Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Models;

namespace BookStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Models;

namespace BookStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent 
    {

        private IBookStoreRepository repository;

        public NavigationMenuViewComponent (IBookStoreRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Views/Shared/BookSummary.cshtml
@model Book

<tr>
    <td>@Model.Title</td>
    <td>@Model.AuthorFirstName</td>
    <td>@Model.AuthorMiddleName</td>
    <td>@Model.AuthorLastName</td>
    <td>@Model.Publisher</td>
    <td>@Model.ISBN</td>
    <td>@Model.Classification</td>
    <td>@Model.Category</td>
    <td>@Model.NumPages</td>
    <td>@Model.Price</td>
    <td>
        <form id="@Model.BookId" asp-page="/Purchase" method="post">
            <input type="hidden" asp-for="BookId" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text p-1">
                <button type="submit" class="btn-success btn-sm pull-right" style="float:right">
                    Add To Cart
                </button>
            </span>
        </form>
    </td>
</tr>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Book Store</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">
        <div class="col-1">
            <vc:navigation-menu />
        </div>
        <div class="text-center">
            <div class="text-center">
                <h1>Let's Look at Some Books</h1>
            </div>
        </div>
        <div class="text-center">
            @RenderBody()
        </div>
    </div>

</body>
</html>